### ISSUE TITLE
Menue "Create from Template" broken

### ISSUE THREAD

**Issue by cDanowski** [52North/smle#31]
When changing to menue "Create from Template" the application crashes with error "Error: Uncaught (in promise): Error: Error in ./Templates class Templates - inline template:6:26 caused by: Cannot read property 'identifier' of undefined".

I am unable to select, filter or browse any template.

**Comment by janschulte** [comment]
Fixed in 3c72c8a1d41322ad65f07bae9225d70eb946daa4
